# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  environment: 'Build Env 1'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: CmdLine@2
  inputs:
    script: 'cmd.exe /C "cmdkey /add:`"coverity202003.file.core.windows.net`" /user:`"Azure\coverity202003`" /pass:`"UUoFiN846Y0M25XpMZgIUPcmtieAD3xoEQSwZf4wSHDVuEqHq2wmrZEfue9sHWxk5o/y4txZcpDZ5so6D7EkNg==`""' 
    #workingDirectory: # Optional
    #failOnStderr: false # Optional
- task: CmdLine@2
  inputs:
    script: 'powershell.exe New-PSDrive -Name Z -PSProvider FileSystem -Root "\\coverity202003.file.core.windows.net\cov2020-03"-Persist'

- task: CmdLine@2
  inputs:
    script: 'z:\c\bin\cov-generate-host-id.exe'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
